### ISSUE TITLE
新版本无法使用，显示缺少依赖

### ISSUE THREAD

**Issue by Kfkcome** [nybuxtsui/clash-tui#2]
第一个版本没有问题，最新的版本有问题，运行不了
![截屏2024-11-11 10 19 15](https://github.com/user-attachments/assets/e12ceb6b-34bc-4559-8b63-cd890e9ada54)

**Comment by nybuxtsui** [comment]
前几天重装电脑，把系统升级到 `ubuntu 24.04` 了，刚找了个旧系统重新编译了一下
你下载 `clash-tui-linux-amd64-musl-v0.1.3.gz` 再试试

**Comment by Kfkcome** [comment]
可以了非常感谢

> 前几天重装电脑，把系统升级到 `ubuntu 24.04` 了，刚找了个旧系统重新编译了一下 你下载 `clash-tui-linux-amd64-musl-v0.1.3.gz` 再试试

**Comment by nybuxtsui** [comment]
> 可以了非常感谢
> 
> > 前几天重装电脑，把系统升级到 `ubuntu 24.04` 了，刚找了个旧系统重新编译了一下 你下载 `clash-tui-linux-amd64-musl-v0.1.3.gz` 再试试

不客气
